name: pymoku-rtd
channels: !!python/tuple
  - conda-forge
  - liquidinstruments
  - defaults
dependencies:
  - conda-forge::ca-certificates=2017.1.23=0
  - conda-forge::certifi=2017.1.23=py27_0
  - conda-forge::decorator=4.0.11=py27_0
  - conda-forge::future=0.16.0=py27_0
  - conda-forge::libsodium=1.0.10=0
  - conda-forge::ncurses=5.9=10
  - conda-forge::openssl=1.0.2h=3
  - conda-forge::pip=9.0.1=py27_0
  - conda-forge::python=2.7.13=0
  - conda-forge::pyzmq=16.0.2=py27_1
  - conda-forge::readline=6.2=0
  - conda-forge::requests=2.13.0=py27_0
  - conda-forge::setuptools=33.1.1=py27_0
  - conda-forge::six=1.10.0=py27_1
  - conda-forge::sqlite=3.13.0=1
  - conda-forge::tk=8.5.19=1
  - conda-forge::urllib3=1.20=py27_1
  - conda-forge::wheel=0.29.0=py27_0
  - conda-forge::zeromq=4.2.1=1
  - conda-forge::zlib=1.2.11=0
  - liquidinstruments::lepl=5.1.3=py27_0
  - liquidinstruments::rfc6266=0.0.4=py27_0
