name: pymoku-rtd
channels: !!python/tuple
  - conda-forge
  - liquidinstruments
  - defaults
dependencies:
  - conda-forge::ca-certificates
  - conda-forge::certifi
  - conda-forge::decorator
  - conda-forge::future
  - conda-forge::libsodium
  - conda-forge::openssl
  - conda-forge::pip
  - conda-forge::pyzmq
  - conda-forge::requests
  - conda-forge::setuptools
  - conda-forge::six
  - conda-forge::urllib3
  - conda-forge::zeromq
  - conda-forge::zlib
  - liquidinstruments::lepl
  - liquidinstruments::rfc6266
