package: 
  name: pymoku
  version: "2.3.0"

source:
  path: .

build:
  number: 0
  entry_points:
    - moku=pymoku.tools.moku:main
    - moku_convert=pymoku.tools.moku_convert:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - future
    - pyzmq >=15.3.0
    - requests >=2.18.0
    - decorator
  run:
    - python
    - future
    - pyzmq >=15.3.0
    - requests >=2.18.0
    - decorator

test:
  imports:
    - pymoku
    - pymoku.tools
  commands:
    - moku --help
    - moku_convert --help

about:
  home: http://github.com/liquidinstruments/pymoku
  license: BSD
  license_file: LICENSE